Addr: "127.0.0.1:8080"
MirrorRegistry: local-registry
OnMissing: |
  ssh <PROXY_SERVER> sh -c '
  docker pull {{.raw}}
  docker tag {{.raw}} {{.mirror}}
  docker push {{.mirror}}
  docker rmi {{.raw}} {{.mirror}}'
Registries:
  - Name: local-registry
    Host: "localhost:5000"
    DockerConfigFile: ${HOME}/.docker/config.json
  - Name: docker-hub
    Host: docker.io
MirrorRules:
  - RawRegName: docker-hub
    MirrorPathTpl: "wweir/{{.Project}}-{{.Repo}}:{{.Tag}}"
